/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AppAdd {}
  interface AppAddAttributes extends StencilHTMLAttributes {}

  interface AppGameoflife {}
  interface AppGameoflifeAttributes extends StencilHTMLAttributes {}

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppIntOperators {}
  interface AppIntOperatorsAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppUniverse {}
  interface AppUniverseAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppAdd': Components.AppAdd;
    'AppGameoflife': Components.AppGameoflife;
    'AppHome': Components.AppHome;
    'AppIntOperators': Components.AppIntOperators;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'AppUniverse': Components.AppUniverse;
  }

  interface StencilIntrinsicElements {
    'app-add': Components.AppAddAttributes;
    'app-gameoflife': Components.AppGameoflifeAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-int-operators': Components.AppIntOperatorsAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'app-universe': Components.AppUniverseAttributes;
  }


  interface HTMLAppAddElement extends Components.AppAdd, HTMLStencilElement {}
  var HTMLAppAddElement: {
    prototype: HTMLAppAddElement;
    new (): HTMLAppAddElement;
  };

  interface HTMLAppGameoflifeElement extends Components.AppGameoflife, HTMLStencilElement {}
  var HTMLAppGameoflifeElement: {
    prototype: HTMLAppGameoflifeElement;
    new (): HTMLAppGameoflifeElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppIntOperatorsElement extends Components.AppIntOperators, HTMLStencilElement {}
  var HTMLAppIntOperatorsElement: {
    prototype: HTMLAppIntOperatorsElement;
    new (): HTMLAppIntOperatorsElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppUniverseElement extends Components.AppUniverse, HTMLStencilElement {}
  var HTMLAppUniverseElement: {
    prototype: HTMLAppUniverseElement;
    new (): HTMLAppUniverseElement;
  };

  interface HTMLElementTagNameMap {
    'app-add': HTMLAppAddElement
    'app-gameoflife': HTMLAppGameoflifeElement
    'app-home': HTMLAppHomeElement
    'app-int-operators': HTMLAppIntOperatorsElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'app-universe': HTMLAppUniverseElement
  }

  interface ElementTagNameMap {
    'app-add': HTMLAppAddElement;
    'app-gameoflife': HTMLAppGameoflifeElement;
    'app-home': HTMLAppHomeElement;
    'app-int-operators': HTMLAppIntOperatorsElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'app-universe': HTMLAppUniverseElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
